### ISSUE TITLE
Add support for Django 1.5

### ISSUE THREAD

**Issue by alinik** [gmcguire/django-db-pool#5]
Hi,
I'm using this db-pool for my app and during the beta testing phase I faced this error:

ImproperlyConfigured: 'dbpool.db.backends.postgresql_psycopg2' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    u'mysql', u'oracle', u'postgresql_psycopg2', u'sqlite3'
Error was: Unsupported Django version 1.5b2
just after the upgrade.

**Comment by anderspetersson** [comment]
This is due to this line: https://github.com/gmcguire/django-db-pool/blob/master/dbpool/db/backends/postgresql_psycopg2/base.py#L225

I've changed this to support 1.4+ in my fork: https://github.com/anderspetersson/django-db-pool
I did however not do any other changes than the actual check for django version, so it would probably need a review or two since I've got absolute none experience writing connection-pooling software.

Currently testing this on production and works fine. Will make pull request when someone with more experience have reviewed my code.

**Comment by gmcguire** [comment]
Yes, Django 1.5 isn't supported yet, as I haven't had a chance to review the 1.5 changes and support them.  If you'd like to contribute a pull request that would be excellent.

**Comment by gmcguire** [comment]
1.5 will make this package's code much simpler.  See this ticket: https://code.djangoproject.com/ticket/19274  I'll try and get 1.5 support done soon.

**Comment by alinik** [comment]
Bump! Django 1.5 released and we need an update for this good app.

**Comment by gmcguire** [comment]
Looks like the nice modularizing from the django ticket above didn't make it into 1.5.  I've added 1.5 support with commit ddce318b7da794c7785e2522e7dbf98b34e90741; please test and let me know how it goes.

**Comment by alinik** [comment]
seems work fine for me. that for the effort, and don't forget to update the pip repo

**Comment by gmcguire** [comment]
Pushed 0.0.9 to pypi.
