### ISSUE TITLE
Possibility to use custom postgres backends with django-db-pool

### ISSUE THREAD

**Issue by KristianOellegaard** [gmcguire/django-db-pool#8]
Hi there,

Would it be possible with an implementation that supports custom backends, such as django-store or the postgis backend?

/Kristian

**Comment by gmcguire** [comment]
@KristianOellegaard In order to add pooling, given the way Django wrote their db connection code, I had to modify the `DatabaseWrapper._cursor` method pretty heavily.  So I think support for each backend will need to be custom, unless someone can offer a more clever solution.

However, the postgis backend looks like a quite light layer over the standard postgresql_psycopg2 driver, so it should be pretty easy to add support for that.  

For other backends, take a look at [base.py](https://github.com/gmcguire/django-db-pool/blob/0.0.8/dbpool/db/backends/postgresql_psycopg2/base.py#L66) and make a pull request!

**Comment by gmcguire** [comment]
Ok, I took a crack at postGIS support; try it out and let me know how it goes.

**Comment by gmcguire** [comment]
Commit is a5a1a3ca7ccb4606136ea00712a457446aefa15d
